export const copy = {
  eraseRecords: ['Effacer mes données dans cette version', 'Erase my data in this version'],
  eraseRecordsConfirm: ['Tes employeurs, quarts et préférences de cette version seront effacés. Exporte une sauvegarde avant de continuer. Tes achats et ton essai ne seront pas réinitialisés. Les données de l’ancienne version sont conservées séparément.', 'Your jobs, shifts and preferences in this version will be erased. Export a backup before continuing. Your purchases and trial will not reset. Data from the old version is kept separately.'],
  accessTitle: ['Accès ProTip365', 'ProTip365 access'],
  accessTrial: ['Jours restants dans ton essai gratuit :', 'Days left in your free trial:'],
  accessExpired: ['Ton essai est terminé. Débloque ProTip365 pour ajouter ou modifier des quarts.', 'Your trial ended. Unlock ProTip365 to add or edit shifts.'],
  accessPaid: ['Ton accès complet est actif.', 'Your full access is active.'],
  accessDataSafe: ['Tes données, tes documents et tes sauvegardes restent accessibles.', 'Your records, documents and backups stay available.'],
  lifetime: ['Accès à vie', 'Lifetime access'],
  monthly: ['Accès mensuel', 'Monthly access'],
  perMonth: ['par mois', 'per month'],
  buyLifetime: ['Débloquer à vie', 'Unlock for life'],
  subscribe: ['M’abonner', 'Subscribe'],
  renewalTerms: ['Renouvellement automatique chaque mois. Annule dans Google Play. Le prix et les conditions sont confirmés avant le paiement.', 'Renews automatically each month. Cancel in Google Play. Price and terms are confirmed before payment.'],
  storeLoading: ['Prix Google Play indisponible. Vérifie ta connexion.', 'Google Play price unavailable. Check your connection.'],
  restorePurchase: ['Restaurer mes achats', 'Restore purchases'],
  manageSubscription: ['Gérer mon abonnement', 'Manage subscription'],
  purchaseSuccess: ['Ton accès complet est actif.', 'Your full access is active.'],
  noPurchases: ['Aucun achat actif trouvé sur ce compte Google Play.', 'No active purchase found on this Google Play account.'],
  purchasePending: ['Paiement en attente. Ton accès sera activé après confirmation par Google Play.', 'Payment pending. Access activates after Google Play confirms it.'],
  storeUnavailable: ['Google Play est indisponible. Réessaie avec le bon compte et une connexion Internet.', 'Google Play is unavailable. Retry with the correct account and an Internet connection.'],
  title: ["Tes quarts.\nTes pourboires.", "Your shifts.\nYour tips."],
  promise: [
    "Ajoute un quart en quelques secondes. Vois tes revenus, chaque semaine, à chaque employeur.",
    "Log a shift in seconds. See what you earn, every week, every job.",
  ],
  privacy: [
    "Sans compte. Tes données restent sur ton téléphone.",
    "No account needed. Your data stays on your phone.",
  ],
  start: ["Commencer", "Get started"],
  import: ["J’utilise déjà une autre app", "I already use another app"],
  importSoon: [
    "L’import depuis une autre app sera offert plus tard. Tu peux déjà restaurer une sauvegarde ProTip365.",
    "Import from another app is coming later. You can already restore a ProTip365 backup.",
  ],
  jobTitle: ["Mon employeur", "My job"],
  employer: ["Employeur", "Employer"],
  name: ["Nom de l’employeur", "Employer name"],
  role: ["Rôle", "Role"],
  server: ["Service", "Server"],
  bartender: ["Bar", "Bartender"],
  busser: ["Commis", "Busser"],
  host: ["Accueil", "Host"],
  barback: ["Aide-bar", "Barback"],
  rate: ["Salaire horaire", "Hourly wage"],
  defaultHours: ["Heures habituelles", "Usual hours"],
  startTime: ["Début", "Start"],
  endTime: ["Fin", "End"],
  break: ["Pause non payée", "Unpaid break"],
  none: ["Aucune", "None"],
  continue: ["Continuer", "Continue"],
  done: ["Terminé", "Done"],
  weekTitle: ["Ma semaine et mes rappels", "My week & reminders"],
  weekStart: ["Ma semaine commence le", "My week starts on"],
  weekHint: [
    "Pour que tes totaux suivent ta paie.",
    "So your totals match your pay period.",
  ],
  reminder: ["Rappel après chaque quart", "End-of-shift reminder"],
  reminderHint: [
    "15 minutes après la fin de tes quarts planifiés.",
    "15 minutes after your planned shifts end.",
  ],
  goal: ["Objectif de pourboires par semaine", "Weekly tip goal"],
  home: ["Accueil", "Home"],
  calendar: ["Calendrier", "Calendar"],
  stats: ["Stats", "Stats"],
  me: ["Moi", "Me"],
  add: ["Ajouter mes pourboires", "Add my tips"],
  week: ["Semaine", "Week"],
  month: ["Mois", "Month"],
  year: ["Année", "Year"],
  tipsWeek: ["MES POURBOIRES CETTE SEMAINE", "MY TIPS THIS WEEK"],
  net: ["Pourboires nets", "Net tips"],
  netHint: [
    "Espèces + carte + part reçue − part donnée",
    "Cash + card + shared in − shared out",
  ],
  hourly: ["Revenu horaire", "Hourly earnings"],
  hourlyHint: [
    "Salaire + pourboires, avant retenues",
    "Wage + tips, before deductions",
  ],
  tipsHour: ["Pourboires par heure", "Tips per hour"],
  hours: ["Heures travaillées", "Hours worked"],
  recent: ["Mes derniers quarts", "Recent shifts"],
  empty: [
    "Ajoute ton premier quart pour voir tes revenus.",
    "Log your first shift to see what you earn.",
  ],
  log: ["Mon quart", "Log a shift"],
  job: ["Quel employeur ?", "Which job?"],
  when: ["Quand ?", "When?"],
  today: ["Aujourd’hui", "Today"],
  yesterday: ["Hier", "Yesterday"],
  other: ["Autre date", "Other date"],
  date: ["Date", "Date"],
  next: ["Suivant : pourboires", "Next: tips"],
  cash: ["Pourboires en espèces", "Cash tips"],
  card: ["Pourboires par carte", "Card tips"],
  cardHint: [
    "Sur ton rapport de fin de quart.",
    "On your end-of-shift report.",
  ],
  in: ["Part reçue de collègues", "Received from the pool"],
  inHint: [
    "Seulement une part non incluse ci-dessus.",
    "Only a share not already included above.",
  ],
  out: ["Part donnée aux collègues", "Given to others (tip-out)"],
  outHint: ["Au bar, à la cuisine, aux commis…", "To bar, kitchen, bussers…"],
  more: ["Plus : ventes et note", "More: sales & note"],
  sales: [
    "Ventes donnant lieu à pourboire, avant taxes",
    "Tippable sales before tax",
  ],
  note: ["Note", "Note"],
  save: ["Enregistrer mon quart", "Save shift"],
  saved: ["Quart enregistré", "Shift saved"],
  undo: ["Annuler l’enregistrement", "Undo save"],
  edit: ["Modifier", "Edit"],
  delete: ["Supprimer", "Delete"],
  cancel: ["Annuler", "Cancel"],
  error: ["À vérifier", "Please check"],
  invalid: [
    "Entre un montant positif ou zéro, avec au plus deux décimales.",
    "Enter a positive amount or zero, with up to two decimal places.",
  ],
  invalidTime: [
    "Vérifie la date, les heures et la pause.",
    "Check the date, times and break.",
  ],
  jobRequired: [
    "Entre le nom de ton employeur.",
    "Enter your employer’s name.",
  ],
  noShift: ["Aucun quart ce jour-là.", "No shift this day."],
  plan: ["Planifier un quart", "Plan a shift"],
  planned: ["Quart planifié", "Planned shift"],
  addDay: ["Ajouter un quart ce jour-là", "Add a shift on this day"],
  average: ["Moyenne par quart", "Average per shift"],
  byJob: ["Par employeur", "By job"],
  bestDay: ["Meilleure journée", "Best day"],
  myJobs: ["Mes employeurs", "My jobs"],
  addJob: ["Ajouter un employeur", "Add a job"],
  archive: ["Archiver cet employeur", "Archive this job"],
  paperwork: ["Mes documents", "My paperwork"],
  statement: ["Relevé pour mon employeur", "Tip statement for my employer"],
  tax: ["Résumé annuel", "Year summary"],
  csv: ["Exporter tous mes quarts (CSV)", "Export all shifts (CSV)"],
  backup: ["Sauvegarder mes données", "Back up my data"],
  restore: ["Restaurer une sauvegarde", "Restore a backup"],
  backupHint: [
    "Un fichier privé à garder pour changer de téléphone.",
    "A private file to keep when changing phones.",
  ],
  settings: ["Préférences", "Settings"],
  language: ["Langue", "Language"],
  from: ["Du", "From"],
  to: ["Au", "To"],
  pdf: ["Partager mon relevé.", "Share PDF"],
  declare: ["Pourboires nets à déclarer", "Net tips to report"],
  statementNote: [
    "Relevé équivalent au registre TP-1019.4-V. Vérifie les montants avant de le remettre à ton employeur.",
    "Statement equivalent to register TP-1019.4-V. Check amounts before giving it to your employer.",
  ],
  eight: [
    "Pourboires directs sous 8 % des ventes renseignées. Une attribution peut s’appliquer; vérifie avec ton employeur.",
    "Direct tips are below 8% of recorded sales. An allocation may apply; check with your employer.",
  ],
  eightHint: [
    "Calcul indicatif sur les quarts avec ventes renseignées. Le taux peut varier selon l’établissement.",
    "Estimate for shifts with recorded sales. The rate can vary by establishment.",
  ],
  lowRate: [
    "Le taux pour les salariés au pourboire au Québec est de 13,30 $/h depuis le 1er mai 2026. Vérifie ton taux.",
    "Québec’s tipped minimum is $13.30/h as of May 1, 2026. Check your rate.",
  ],
  noData: ["Pas encore de données", "No data yet"],
  restoreConfirm: [
    "Remplacer les données actuelles ? Une sauvegarde sera créée avant le remplacement.",
    "Replace current data? A backup will be created before replacement.",
  ],
  storageError: [
    "Impossible de sauvegarder. Tes modifications restent ouvertes; réessaie.",
    "Could not save. Your changes remain open; try again.",
  ],
  loadError: [
    "Impossible de lire tes données. Elles n’ont pas été effacées.",
    "Could not read your data. It has not been erased.",
  ],
  retry: ["Réessayer", "Retry"],
  overnight: ["Fin le lendemain", "Ends next day"],
  reminderDenied: [
    "Les rappels sont désactivés dans Android. Tu peux les autoriser dans les réglages du téléphone.",
    "Reminders are disabled in Android. Enable them in your phone settings.",
  ],
  hello: ["Bonjour", "Hi"],
  goalProgress: ["de ton objectif", "of your goal"],
  comparison: [
    "de plus que ta moyenne ce jour-là",
    "more than your average for this weekday",
  ],
  tipOther: [
    "Autres pourboires directs (valet, livraison…)",
    "Other direct tips (valet, delivery…)",
  ],
  help: ["Aide", "Help"],
  privacyLink: ["Confidentialité", "Privacy"],
  terms: ["Conditions", "Terms"],
  back: ["Retour", "Back"],
  notification: [
    "Comment était ton quart ? Ajoute tes pourboires.",
    "How was your shift? Add your tips.",
  ],
  snooze: ["Demain matin", "Tomorrow morning"],
  logged: ["quarts enregistrés", "shifts logged"],
  loggedOne: ["quart enregistré", "shift logged"],
  saveGoal: ["Enregistrer mon objectif", "Save my goal"],
  previousMonth: ["Mois précédent", "Previous month"],
  nextMonth: ["Mois suivant", "Next month"],
  nameUser: ["Prénom (facultatif)", "First name (optional)"],
  deleteConfirm: [
    "Supprimer ce quart ? Tu peux annuler juste après.",
    "Delete this shift? You can undo immediately after.",
  ],
  restoreError: [
    "Ce fichier n’est pas une sauvegarde ProTip365 valide.",
    "This file is not a valid ProTip365 backup.",
  ],
  exportError: [
    "Impossible de créer ou partager le fichier. Réessaie.",
    "Could not create or share the file. Try again.",
  ],
  notifyError: [
    "Impossible de programmer les rappels. Réessaie dans les préférences.",
    "Could not schedule reminders. Try again in settings.",
  ],
} as const;
export type CopyKey = keyof typeof copy;
export const text = (key: CopyKey, lang: "fr" | "en"): string =>
  copy[key][lang === "fr" ? 0 : 1];

export const roleLabel = (role: string, t: (key: CopyKey) => string) => {
  const key = (
    {
      Server: "server",
      Bartender: "bartender",
      Busser: "busser",
      Host: "host",
      Barback: "barback",
    } as Record<string, CopyKey>
  )[role];
  return key ? t(key) : role;
};
