-- Deprecated for security: public email existence checks allow account enumeration.
-- Keep this migration as a no-op for fresh environments. Existing deployments are
-- cleaned up by 20260510000000_remove_email_existence_oracle.sql.
