// Canonical geometry from https://www.protip365.com/ (verified October 3, 2026):
// 48x48, rx=12, sage #8A9C7D, Fraunces 600 "p." at x=23/y=34,
// font-size 32, text-anchor middle, cream #FBFAF6.
const fs = require("node:fs");
const path = require("node:path");
const { createCanvas, Path2D } = require("@napi-rs/canvas");
const bytes = fs.readFileSync(
  path.resolve(
    "node_modules/@expo-google-fonts/fraunces/600SemiBold/Fraunces_600SemiBold.ttf",
  ),
);
const font = require("opentype.js").parse(
  bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength),
);
const sage = "#8A9C7D", cream = "#FBFAF6";
const glyphs = font.getPath("p.", 23 - font.getAdvanceWidth("p.", 32) / 2, 34, 32);
const markPath = glyphs.toPathData(4);
fs.writeFileSync(path.resolve("src/brand.ts"),
  `// Generated by scripts/create-brand.cjs from the landing-page logo.\nexport const brand = ${JSON.stringify({sage, cream, markPath}, null, 2)} as const;\n`);
fs.writeFileSync(path.resolve("assets/logo.svg"),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><rect width="48" height="48" rx="12" fill="${sage}"/><path d="${markPath}" fill="${cream}"/></svg>\n`);
function make(file, size, foreground = false, monochrome = false, rounded = false) {
  const canvas = createCanvas(size, size),
    c = canvas.getContext("2d");
  if (!foreground) {
    c.fillStyle = sage;
    c.beginPath();
    c.roundRect(0, 0, size, size, rounded ? size * 0.25 : 0);
    c.fill();
  }
  c.fillStyle = monochrome ? "#000000" : cream;
  // Keep the adaptive mark inside Android's central safe area.
  const frame = size * (foreground ? 0.62 : 1);
  c.translate((size - frame) / 2, (size - frame) / 2);
  c.scale(frame / 48, frame / 48);
  c.fill(new Path2D(markPath));
  fs.writeFileSync(path.resolve("assets", file), canvas.toBuffer("image/png"));
}
make("icon.png", 1024);
make("android-icon-foreground.png", 1024, true);
make("android-icon-monochrome.png", 1024, true, true);
make("splash-logo.png", 200, false, false, true);
make("favicon.png", 64, false, false, true);
